apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: flask-mongodb-app:v1
          imagePullPolicy: Never # Crucial: tells K8s to look locally inside minikube's registry
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: MONGO_HOST
              value: "mongodb-service"
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m" # 0.2 CPU as requested
            limits:
              memory: "500Mi"
              cpu: "500m" # 0.5 CPU as requested
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort # Exposes the port out to your local Windows machine
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
  selector:
    app: flask-app
